# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Python/py_record_psd/ui/record\mainwindow.ui'
#
# Created: Fri Jul 21 01:45:38 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(346, 537)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.SaveSizeWidthLineEdit = QtGui.QLineEdit(self.centralWidget)
        self.SaveSizeWidthLineEdit.setObjectName("SaveSizeWidthLineEdit")
        self.gridLayout.addWidget(self.SaveSizeWidthLineEdit, 5, 0, 1, 1)
        self.ShowDirectoryButton = QtGui.QPushButton(self.centralWidget)
        self.ShowDirectoryButton.setObjectName("ShowDirectoryButton")
        self.gridLayout.addWidget(self.ShowDirectoryButton, 3, 1, 1, 1)
        self.SaveSizeHeightLineEdit = QtGui.QLineEdit(self.centralWidget)
        self.SaveSizeHeightLineEdit.setObjectName("SaveSizeHeightLineEdit")
        self.gridLayout.addWidget(self.SaveSizeHeightLineEdit, 5, 1, 1, 1)
        self.StopButton = QtGui.QPushButton(self.centralWidget)
        self.StopButton.setObjectName("StopButton")
        self.gridLayout.addWidget(self.StopButton, 10, 1, 1, 1)
        self.FrameRateLineEdit = QtGui.QLineEdit(self.centralWidget)
        self.FrameRateLineEdit.setObjectName("FrameRateLineEdit")
        self.gridLayout.addWidget(self.FrameRateLineEdit, 10, 0, 1, 1)
        self.MakeDivisable16Button = QtGui.QPushButton(self.centralWidget)
        self.MakeDivisable16Button.setObjectName("MakeDivisable16Button")
        self.gridLayout.addWidget(self.MakeDivisable16Button, 3, 0, 1, 1)
        self.StartButton = QtGui.QPushButton(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartButton.sizePolicy().hasHeightForWidth())
        self.StartButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.StartButton.setFont(font)
        self.StartButton.setObjectName("StartButton")
        self.gridLayout.addWidget(self.StartButton, 7, 1, 1, 1)
        self.FileTypeComboBox = QtGui.QComboBox(self.centralWidget)
        self.FileTypeComboBox.setObjectName("FileTypeComboBox")
        self.FileTypeComboBox.addItem("")
        self.FileTypeComboBox.addItem("")
        self.gridLayout.addWidget(self.FileTypeComboBox, 7, 0, 1, 1)
        self.AlwaysOnTopCheckbox = QtGui.QCheckBox(self.centralWidget)
        self.AlwaysOnTopCheckbox.setChecked(True)
        self.AlwaysOnTopCheckbox.setObjectName("AlwaysOnTopCheckbox")
        self.gridLayout.addWidget(self.AlwaysOnTopCheckbox, 6, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PreviewLabel = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PreviewLabel.sizePolicy().hasHeightForWidth())
        self.PreviewLabel.setSizePolicy(sizePolicy)
        self.PreviewLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PreviewLabel.setObjectName("PreviewLabel")
        self.horizontalLayout_2.addWidget(self.PreviewLabel)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 2)
        self.AutoSaveCheckbox = QtGui.QCheckBox(self.centralWidget)
        self.AutoSaveCheckbox.setChecked(True)
        self.AutoSaveCheckbox.setObjectName("AutoSaveCheckbox")
        self.gridLayout.addWidget(self.AutoSaveCheckbox, 6, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PSDPathLineInput = QtGui.QLineEdit(self.centralWidget)
        self.PSDPathLineInput.setObjectName("PSDPathLineInput")
        self.horizontalLayout.addWidget(self.PSDPathLineInput)
        self.RefreshPSDirectoryButton = QtGui.QPushButton(self.centralWidget)
        self.RefreshPSDirectoryButton.setObjectName("RefreshPSDirectoryButton")
        self.horizontalLayout.addWidget(self.RefreshPSDirectoryButton)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.MakeDivisable16Button, self.SaveSizeWidthLineEdit)
        MainWindow.setTabOrder(self.SaveSizeWidthLineEdit, self.FrameRateLineEdit)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PSDRecorder", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveSizeWidthLineEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "WIdth", None, QtGui.QApplication.UnicodeUTF8))
        self.ShowDirectoryButton.setText(QtGui.QApplication.translate("MainWindow", "Explore Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveSizeHeightLineEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.StopButton.setText(QtGui.QApplication.translate("MainWindow", "Stop/Encode GIF/MP4", None, QtGui.QApplication.UnicodeUTF8))
        self.StopButton.setShortcut(QtGui.QApplication.translate("MainWindow", "Esc", None, QtGui.QApplication.UnicodeUTF8))
        self.FrameRateLineEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Framerate", None, QtGui.QApplication.UnicodeUTF8))
        self.MakeDivisable16Button.setText(QtGui.QApplication.translate("MainWindow", "Resize d16", None, QtGui.QApplication.UnicodeUTF8))
        self.StartButton.setText(QtGui.QApplication.translate("MainWindow", "Record", None, QtGui.QApplication.UnicodeUTF8))
        self.StartButton.setShortcut(QtGui.QApplication.translate("MainWindow", "Return", None, QtGui.QApplication.UnicodeUTF8))
        self.FileTypeComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "jpg", None, QtGui.QApplication.UnicodeUTF8))
        self.FileTypeComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "png", None, QtGui.QApplication.UnicodeUTF8))
        self.AlwaysOnTopCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Always on top", None, QtGui.QApplication.UnicodeUTF8))
        self.AlwaysOnTopCheckbox.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.PreviewLabel.setText(QtGui.QApplication.translate("MainWindow", "[Preview Here]", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.AutoSaveCheckbox.setText(QtGui.QApplication.translate("MainWindow", "Auto Save Photoshop", None, QtGui.QApplication.UnicodeUTF8))
        self.AutoSaveCheckbox.setShortcut(QtGui.QApplication.translate("MainWindow", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.PSDPathLineInput.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Active PSD Path", None, QtGui.QApplication.UnicodeUTF8))
        self.RefreshPSDirectoryButton.setText(QtGui.QApplication.translate("MainWindow", "<- Photoshop", None, QtGui.QApplication.UnicodeUTF8))

