# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\py_record_psd\ui\record\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(369, 507)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.ShowDirectoryButton = QtWidgets.QPushButton(self.centralWidget)
        self.ShowDirectoryButton.setObjectName("ShowDirectoryButton")
        self.gridLayout.addWidget(self.ShowDirectoryButton, 3, 1, 1, 1)
        self.FrameRateLineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.FrameRateLineEdit.setObjectName("FrameRateLineEdit")
        self.gridLayout.addWidget(self.FrameRateLineEdit, 11, 0, 1, 1)
        self.MakeDivisable16Button = QtWidgets.QPushButton(self.centralWidget)
        self.MakeDivisable16Button.setObjectName("MakeDivisable16Button")
        self.gridLayout.addWidget(self.MakeDivisable16Button, 3, 0, 1, 1)
        self.SaveSizeWidthLineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.SaveSizeWidthLineEdit.setObjectName("SaveSizeWidthLineEdit")
        self.gridLayout.addWidget(self.SaveSizeWidthLineEdit, 5, 0, 1, 1)
        self.SaveSizeHeightLineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.SaveSizeHeightLineEdit.setObjectName("SaveSizeHeightLineEdit")
        self.gridLayout.addWidget(self.SaveSizeHeightLineEdit, 5, 1, 1, 1)
        self.StopButton = QtWidgets.QPushButton(self.centralWidget)
        self.StopButton.setObjectName("StopButton")
        self.gridLayout.addWidget(self.StopButton, 11, 1, 1, 1)
        self.FileTypeComboBox = QtWidgets.QComboBox(self.centralWidget)
        self.FileTypeComboBox.setObjectName("FileTypeComboBox")
        self.FileTypeComboBox.addItem("")
        self.FileTypeComboBox.addItem("")
        self.gridLayout.addWidget(self.FileTypeComboBox, 8, 0, 1, 1)
        self.StartButton = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartButton.sizePolicy().hasHeightForWidth())
        self.StartButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.StartButton.setFont(font)
        self.StartButton.setObjectName("StartButton")
        self.gridLayout.addWidget(self.StartButton, 8, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PreviewLabel = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PreviewLabel.sizePolicy().hasHeightForWidth())
        self.PreviewLabel.setSizePolicy(sizePolicy)
        self.PreviewLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PreviewLabel.setObjectName("PreviewLabel")
        self.horizontalLayout_2.addWidget(self.PreviewLabel)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.PaletteGrpView = QtWidgets.QGraphicsView(self.tab_2)
        self.PaletteGrpView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.PaletteGrpView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.PaletteGrpView.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.PaletteGrpView.setObjectName("PaletteGrpView")
        self.horizontalLayout_3.addWidget(self.PaletteGrpView)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 2)
        self.CloseWhenDoneCheckbox = QtWidgets.QCheckBox(self.centralWidget)
        self.CloseWhenDoneCheckbox.setChecked(True)
        self.CloseWhenDoneCheckbox.setObjectName("CloseWhenDoneCheckbox")
        self.gridLayout.addWidget(self.CloseWhenDoneCheckbox, 6, 1, 1, 1)
        self.AutoSaveCheckbox = QtWidgets.QCheckBox(self.centralWidget)
        self.AutoSaveCheckbox.setChecked(True)
        self.AutoSaveCheckbox.setObjectName("AutoSaveCheckbox")
        self.gridLayout.addWidget(self.AutoSaveCheckbox, 6, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PSDPathLineInput = QtWidgets.QLineEdit(self.centralWidget)
        self.PSDPathLineInput.setObjectName("PSDPathLineInput")
        self.horizontalLayout.addWidget(self.PSDPathLineInput)
        self.RefreshPSDirectoryButton = QtWidgets.QPushButton(self.centralWidget)
        self.RefreshPSDirectoryButton.setObjectName("RefreshPSDirectoryButton")
        self.horizontalLayout.addWidget(self.RefreshPSDirectoryButton)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        self.ClearCacheCheckbox = QtWidgets.QCheckBox(self.centralWidget)
        self.ClearCacheCheckbox.setChecked(True)
        self.ClearCacheCheckbox.setObjectName("ClearCacheCheckbox")
        self.gridLayout.addWidget(self.ClearCacheCheckbox, 7, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.MakeDivisable16Button, self.SaveSizeWidthLineEdit)
        MainWindow.setTabOrder(self.SaveSizeWidthLineEdit, self.FrameRateLineEdit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PSDRecorder"))
        self.ShowDirectoryButton.setText(_translate("MainWindow", "Explore Directory"))
        self.FrameRateLineEdit.setPlaceholderText(_translate("MainWindow", "Framerate"))
        self.MakeDivisable16Button.setText(_translate("MainWindow", "Resize d16"))
        self.SaveSizeWidthLineEdit.setPlaceholderText(_translate("MainWindow", "WIdth"))
        self.SaveSizeHeightLineEdit.setPlaceholderText(_translate("MainWindow", "Height"))
        self.StopButton.setText(_translate("MainWindow", "Stop/Encode GIF/MP4"))
        self.StopButton.setShortcut(_translate("MainWindow", "Esc"))
        self.FileTypeComboBox.setItemText(0, _translate("MainWindow", "jpg"))
        self.FileTypeComboBox.setItemText(1, _translate("MainWindow", "png"))
        self.StartButton.setText(_translate("MainWindow", "Record"))
        self.StartButton.setShortcut(_translate("MainWindow", "Return"))
        self.PreviewLabel.setText(_translate("MainWindow", "[Preview Here]"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Preview"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Palette"))
        self.CloseWhenDoneCheckbox.setText(_translate("MainWindow", "Close when done"))
        self.CloseWhenDoneCheckbox.setShortcut(_translate("MainWindow", "S"))
        self.AutoSaveCheckbox.setText(_translate("MainWindow", "Auto Save Photoshop"))
        self.AutoSaveCheckbox.setShortcut(_translate("MainWindow", "S"))
        self.PSDPathLineInput.setPlaceholderText(_translate("MainWindow", "Active PSD Path"))
        self.RefreshPSDirectoryButton.setText(_translate("MainWindow", "<- Photoshop"))
        self.ClearCacheCheckbox.setText(_translate("MainWindow", "Clear Cache"))
        self.ClearCacheCheckbox.setShortcut(_translate("MainWindow", "S"))

